services:
  - type: web
    name: familylinx-web
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python manage.py migrate && python manage.py collectstatic --noinput && gunicorn config.wsgi:application
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: ""
      - key: CSRF_TRUSTED_ORIGINS
        value: ""
      - key: DATABASE_URL
        fromDatabase:
          name: familylinx-db
          property: connectionString
      - key: CLOUDINARY_URL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: ""
      - key: CORS_ALLOW_CREDENTIALS
        value: "true"
      - key: CSRF_TRUSTED_ORIGINS
        value: ""
    healthCheckPath: /
    autoSslCert: true

databases:
  - name: familylinx-db
    plan: free
    region: oregon
