# Generated by Django 6.0.2 on 2026-02-23 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0008_dnakit_dnamatch_relationshipsuggestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(max_length=5000)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by_sender', models.BooleanField(default=False)),
                ('deleted_by_recipient', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_profile_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_profile_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Message',
                'verbose_name_plural': 'Profile Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfilePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Post content', max_length=2000)),
                ('image', models.ImageField(blank=True, help_text='Optional image attachment', null=True, upload_to='profiles/posts/')),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('MEMBERS', 'Family Members'), ('PRIVATE', 'Only Me')], default='MEMBERS', max_length=10)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='User who wrote the post', on_delete=django.db.models.deletion.CASCADE, related_name='profile_posts_authored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Post',
                'verbose_name_plural': 'Profile Posts',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfilePostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_post_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.profilepost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='Name shown on profile (defaults to email username)', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Tell us about yourself', max_length=500)),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile picture (recommended: 180x180px)', null=True, upload_to='profiles/avatars/')),
                ('cover_photo', models.ImageField(blank=True, help_text='Cover photo (recommended: 820x312px)', null=True, upload_to='profiles/covers/')),
                ('location', models.CharField(blank=True, help_text='Where you live', max_length=100)),
                ('website', models.URLField(blank=True, help_text='Your personal website')),
                ('date_of_birth', models.DateField(blank=True, help_text='Your birth date', null=True)),
                ('profile_visibility', models.CharField(choices=[('PUBLIC', 'Public - Anyone can see'), ('MEMBERS', 'Family Members Only'), ('PRIVATE', 'Private - Only me')], default='MEMBERS', help_text='Who can see your profile', max_length=10)),
                ('show_email', models.BooleanField(default=False, help_text='Show email address on profile')),
                ('show_birthday', models.BooleanField(default=True, help_text='Show birthday on profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_person', models.ForeignKey(blank=True, help_text='Link this profile to a person in the family tree', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='families.person')),
                ('user', models.OneToOneField(help_text='User this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.AddField(
            model_name='profilepost',
            name='profile',
            field=models.ForeignKey(help_text='Profile this post is on', on_delete=django.db.models.deletion.CASCADE, related_name='wall_posts', to='accounts.userprofile'),
        ),
    ]
