# Generated by Django 6.0.2 on 2026-02-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepost',
            name='video',
            field=models.FileField(blank=True, help_text='Optional video attachment', null=True, upload_to='profiles/videos/'),
        ),
    ]
