# Generated by Django 6.0.2 on 2026-03-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_video_to_profile_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_activity",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time the user was active on the site",
                null=True,
            ),
        ),
    ]
