# Generated by Django 6.0.2 on 2026-03-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_last_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="middle_name",
            field=models.CharField(blank=True, help_text="Your middle name", max_length=100),
        ),
    ]
