# Generated by Django 6.0.2 on 2026-02-22 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilySpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the family space', max_length=120)),
                ('description', models.TextField(blank=True, help_text='Optional description of the family space')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when space was created')),
                ('root_person_1_id', models.BigIntegerField(blank=True, help_text='Future: ID of first root person in family tree', null=True)),
                ('root_person_2_id', models.BigIntegerField(blank=True, help_text='Future: ID of second root person in family tree', null=True)),
                ('created_by', models.ForeignKey(help_text='User who created this family space', on_delete=django.db.models.deletion.PROTECT, related_name='created_families', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Family Space',
                'verbose_name_plural': 'Family Spaces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address to send the invite to', max_length=254)),
                ('token', models.CharField(editable=False, help_text='Secure token for invite URL (auto-generated)', max_length=64, unique=True)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('EDITOR', 'Editor'), ('MEMBER', 'Member'), ('VIEWER', 'Viewer')], default='MEMBER', help_text='Role to assign when invite is accepted', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the invite was created')),
                ('expires_at', models.DateTimeField(help_text='When the invite expires (default: 14 days from creation)')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the invite was accepted (null if pending)', null=True)),
                ('created_by', models.ForeignKey(help_text='User who created this invite', on_delete=django.db.models.deletion.PROTECT, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(help_text='Family space this invite is for', on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='families.familyspace')),
            ],
            options={
                'verbose_name': 'Invite',
                'verbose_name_plural': 'Invites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('EDITOR', 'Editor'), ('MEMBER', 'Member'), ('VIEWER', 'Viewer')], default='MEMBER', help_text='Permission level for this membership', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when user joined the family space')),
                ('family', models.ForeignKey(help_text='The family space this membership belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='families.familyspace')),
                ('user', models.ForeignKey(help_text='The user who has this membership', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
                'ordering': ['joined_at'],
                'unique_together': {('family', 'user')},
            },
        ),
    ]
