# Generated by Django 6.0.2 on 2026-02-22 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The text content of the post')),
                ('image', models.ImageField(blank=True, help_text='Optional image attachment', null=True, upload_to='posts/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the post was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the post was last modified')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin this post to the top of the feed')),
                ('is_hidden', models.BooleanField(default=False, help_text='Hide this post (moderation)')),
                ('author', models.ForeignKey(help_text='The user who created this post', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(help_text='The family space this post belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='families.familyspace')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The comment text')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the comment was created')),
                ('is_hidden', models.BooleanField(default=False, help_text='Hide this comment (moderation)')),
                ('author', models.ForeignKey(help_text='The user who wrote this comment', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(help_text='The post this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='families.post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['created_at'],
            },
        ),
    ]
