# Generated by Django 6.0.2 on 2026-02-22 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_post_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Event description and details')),
                ('event_type', models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('REUNION', 'Family Reunion'), ('HOLIDAY', 'Holiday Gathering'), ('ANNIVERSARY', 'Anniversary'), ('MEMORIAL', 'Memorial'), ('OTHER', 'Other')], default='OTHER', help_text='Type of event', max_length=20)),
                ('start_datetime', models.DateTimeField(help_text='When the event starts')),
                ('end_datetime', models.DateTimeField(blank=True, help_text='When the event ends (optional)', null=True)),
                ('location', models.CharField(blank=True, help_text='Event location/address', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this event was created')),
                ('created_by', models.ForeignKey(help_text='User who created this event', on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(help_text='The family this event belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='families.familyspace')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('GOING', 'Going'), ('MAYBE', 'Maybe'), ('NOT_GOING', 'Not Going')], help_text='RSVP status', max_length=10)),
                ('responded_at', models.DateTimeField(auto_now=True, help_text='When the RSVP was submitted/updated')),
                ('event', models.ForeignKey(help_text='The event being responded to', on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='families.event')),
                ('user', models.ForeignKey(help_text='The user responding', on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RSVP',
                'verbose_name_plural': 'RSVPs',
                'unique_together': {('event', 'user')},
            },
        ),
    ]
