# Generated by Django 6.0.2 on 2026-02-22 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0003_event_rsvp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First/given name', max_length=100)),
                ('last_name', models.CharField(help_text='Family/surname', max_length=100)),
                ('maiden_name', models.CharField(blank=True, help_text='Birth surname if different (e.g., before marriage)', max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], default='U', help_text='Gender', max_length=1)),
                ('birth_date', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('death_date', models.DateField(blank=True, help_text='Date of death (leave blank if living)', null=True)),
                ('birth_place', models.CharField(blank=True, help_text='Place of birth', max_length=200)),
                ('death_place', models.CharField(blank=True, help_text='Place of death', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Biography, notes, or stories about this person')),
                ('photo', models.ImageField(blank=True, help_text='Profile photo', null=True, upload_to='persons/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('created_by', models.ForeignKey(help_text='User who added this person', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons_created', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(help_text='The family this person belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='families.familyspace')),
                ('linked_user', models.OneToOneField(blank=True, help_text='Link to a FamilyLinx user account (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('PARENT_CHILD', 'Parent-Child'), ('SPOUSE', 'Spouse')], help_text='Type of relationship', max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='Start date (e.g., marriage date)', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date (e.g., divorce date)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this relationship')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this relationship was recorded')),
                ('family', models.ForeignKey(help_text='The family this relationship belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='families.familyspace')),
                ('person1', models.ForeignKey(help_text='First person (parent in parent-child, either in spouse)', on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='families.person')),
                ('person2', models.ForeignKey(help_text='Second person (child in parent-child, either in spouse)', on_delete=django.db.models.deletion.CASCADE, related_name='child_relationships', to='families.person')),
            ],
            options={
                'verbose_name': 'Relationship',
                'verbose_name_plural': 'Relationships',
                'unique_together': {('person1', 'person2', 'relationship_type')},
            },
        ),
    ]
