# Generated by Django 6.0.2 on 2026-02-23 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0004_person_relationship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Album title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of this album')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this album was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this album was last modified')),
                ('created_by', models.ForeignKey(help_text='User who created this album', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_albums', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(help_text='The family space this album belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='families.familyspace')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='The photo image file', upload_to='photos/%Y/%m/')),
                ('caption', models.CharField(blank=True, help_text='Caption or description for this photo', max_length=500)),
                ('taken_date', models.DateField(blank=True, help_text='Date the photo was taken', null=True)),
                ('taken_location', models.CharField(blank=True, help_text='Location where the photo was taken', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When this photo was uploaded')),
                ('album', models.ForeignKey(help_text='The album this photo belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='families.album')),
                ('tagged_people', models.ManyToManyField(blank=True, help_text='People appearing in this photo', related_name='tagged_photos', to='families.person')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this photo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['-taken_date', '-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='cover_photo',
            field=models.ForeignKey(blank=True, help_text='Cover photo for this album', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='families.photo'),
        ),
    ]
