# Generated by Django 6.0.2 on 2026-02-23 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0005_album_photo_album_cover_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Message text content', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When message was sent')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag for moderation')),
                ('author', models.ForeignKey(help_text='User who sent this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(help_text='Family space this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='families.familyspace')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['family', 'created_at'], name='families_ch_family__2d4cbd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('POST', 'New Post'), ('COMMENT', 'New Comment'), ('EVENT', 'Event Update'), ('INVITE', 'Invitation'), ('RSVP', 'RSVP Update'), ('PHOTO', 'New Photo'), ('PERSON', 'Family Tree Update'), ('CHAT', 'New Message'), ('SYSTEM', 'System Alert')], default='SYSTEM', help_text='Type of notification', max_length=20)),
                ('title', models.CharField(help_text='Short notification title', max_length=200)),
                ('message', models.TextField(blank=True, help_text='Notification content/body')),
                ('link', models.CharField(blank=True, help_text='URL to navigate to when notification is clicked', max_length=500)),
                ('is_read', models.BooleanField(default=False, help_text='Whether user has seen this notification')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When notification was created')),
                ('family', models.ForeignKey(blank=True, help_text='Family space context for this notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='families.familyspace')),
                ('recipient', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='families_no_recipie_2e3fc5_idx'), models.Index(fields=['recipient', 'is_read'], name='families_no_recipie_93f155_idx')],
            },
        ),
    ]
