# Generated by Django 6.0.2 on 2026-02-23 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0006_chatmessage_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GedcomImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current processing status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When import was initiated')),
                ('started_at', models.DateTimeField(blank=True, help_text='When processing started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When processing completed', null=True)),
                ('persons_created', models.PositiveIntegerField(default=0)),
                ('persons_updated', models.PositiveIntegerField(default=0)),
                ('relationships_created', models.PositiveIntegerField(default=0)),
                ('duplicates_found', models.PositiveIntegerField(default=0)),
                ('errors', models.TextField(blank=True, default='[]', help_text='JSON array of error messages')),
                ('family', models.ForeignKey(help_text='Family space to import into', on_delete=django.db.models.deletion.CASCADE, related_name='gedcom_imports', to='families.familyspace')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gedcom_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GEDCOM Import',
                'verbose_name_plural': 'GEDCOM Imports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PotentialDuplicate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=0, help_text='Match confidence score (0-100)')),
                ('match_reasons', models.TextField(blank=True, default='[]', help_text='JSON array of match reasons')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('MERGED', 'Merged'), ('KEPT_BOTH', 'Kept Both'), ('DISMISSED', 'Dismissed')], default='PENDING', help_text='Review status', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the duplicate was reviewed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When duplicate was detected')),
                ('existing_person', models.ForeignKey(help_text='The existing person in database', on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_matches_existing', to='families.person')),
                ('gedcom_import', models.ForeignKey(help_text='The import that found this duplicate', on_delete=django.db.models.deletion.CASCADE, related_name='potential_duplicates', to='families.gedcomimport')),
                ('imported_person', models.ForeignKey(help_text='The newly imported person', on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_matches_imported', to='families.person')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='User who reviewed this duplicate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_duplicates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Potential Duplicate',
                'verbose_name_plural': 'Potential Duplicates',
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
    ]
