# Generated by Django 6.0.2 on 2026-02-23 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0007_gedcomimport_potentialduplicate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DNAKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ANCESTRY', 'AncestryDNA'), ('23ANDME', '23andMe'), ('FTDNA', 'FamilyTreeDNA'), ('MYHERITAGE', 'MyHeritage'), ('LIVINGDNA', 'LivingDNA'), ('GEDMATCH', 'GEDmatch'), ('OTHER', 'Other')], default='ANCESTRY', help_text='DNA testing provider', max_length=20)),
                ('kit_id', models.CharField(blank=True, help_text='Kit identifier from provider (optional)', max_length=100)),
                ('display_name', models.CharField(help_text='Friendly name for this kit', max_length=100)),
                ('is_private', models.BooleanField(default=True, help_text='If True, kit is hidden from other users')),
                ('allow_matching', models.BooleanField(default=False, help_text='If True, allow DNA matching with other users')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When kit was registered')),
                ('notes', models.TextField(blank=True, help_text='Private notes about this kit')),
                ('linked_person', models.ForeignKey(blank=True, help_text='Person in family tree this kit belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dna_kits', to='families.person')),
                ('user', models.ForeignKey(help_text='Owner of this DNA kit', on_delete=django.db.models.deletion.CASCADE, related_name='dna_kits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DNA Kit',
                'verbose_name_plural': 'DNA Kits',
                'ordering': ['-uploaded_at'],
                'unique_together': {('user', 'provider', 'kit_id')},
            },
        ),
        migrations.CreateModel(
            name='DNAMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_cm', models.FloatField(help_text='Shared DNA in centiMorgans')),
                ('shared_segments', models.PositiveIntegerField(default=0, help_text='Number of shared DNA segments')),
                ('largest_segment', models.FloatField(default=0, help_text='Largest shared segment in cM')),
                ('predicted_relationship', models.CharField(blank=True, help_text='Estimated relationship based on cM', max_length=100)),
                ('confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', help_text='Confidence level of prediction', max_length=10)),
                ('is_confirmed', models.BooleanField(default=False, help_text='Both users confirmed this match')),
                ('confirmed_by_kit1', models.BooleanField(default=False, help_text='Kit1 owner confirmed')),
                ('confirmed_by_kit2', models.BooleanField(default=False, help_text='Kit2 owner confirmed')),
                ('discovered_at', models.DateTimeField(auto_now_add=True, help_text='When match was recorded')),
                ('notes', models.TextField(blank=True, help_text='Notes about this match')),
                ('kit1', models.ForeignKey(help_text='First kit in the match', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_kit1', to='families.dnakit')),
                ('kit2', models.ForeignKey(help_text='Second kit in the match', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_kit2', to='families.dnakit')),
            ],
            options={
                'verbose_name': 'DNA Match',
                'verbose_name_plural': 'DNA Matches',
                'ordering': ['-shared_cm'],
                'unique_together': {('kit1', 'kit2')},
            },
        ),
        migrations.CreateModel(
            name='RelationshipSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_relationship', models.CharField(help_text='Suggested relationship type', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('IGNORED', 'Ignored')], default='PENDING', help_text='Suggestion status', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the suggestion was reviewed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When suggestion was created')),
                ('notes', models.TextField(blank=True, help_text='Notes about the decision')),
                ('dna_match', models.ForeignKey(help_text='The DNA match this suggestion is based on', on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='families.dnamatch')),
                ('family', models.ForeignKey(help_text='Family space for this suggestion', on_delete=django.db.models.deletion.CASCADE, related_name='dna_suggestions', to='families.familyspace')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='User who reviewed this suggestion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_dna_suggestions', to=settings.AUTH_USER_MODEL)),
                ('suggested_for_kit', models.ForeignKey(help_text='Kit owner receiving this suggestion', on_delete=django.db.models.deletion.CASCADE, related_name='relationship_suggestions', to='families.dnakit')),
                ('suggested_person', models.ForeignKey(blank=True, help_text='Existing person to link with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dna_suggestions', to='families.person')),
            ],
            options={
                'verbose_name': 'Relationship Suggestion',
                'verbose_name_plural': 'Relationship Suggestions',
                'ordering': ['-created_at'],
            },
        ),
    ]
