# Generated by Django 6.0.2 on 2026-02-23 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0008_dnakit_dnamatch_relationshipsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='source_import',
            field=models.ForeignKey(blank=True, help_text='GEDCOM import that created this person (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_persons', to='families.gedcomimport'),
        ),
    ]
