# Generated by Django 6.0.2 on 2026-02-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0009_add_source_import_to_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Event cover image or flyer', null=True, upload_to='events/'),
        ),
    ]
