# Generated by Django 6.0.2 on 2026-02-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0010_add_image_to_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_date_qualifier',
            field=models.CharField(blank=True, help_text='Date qualifier: ABT (about), BEF (before), AFT (after), EST (estimated)', max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='death_date_qualifier',
            field=models.CharField(blank=True, help_text='Date qualifier: ABT (about), BEF (before), AFT (after), EST (estimated)', max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Mark as private to hide details from non-family viewers'),
        ),
    ]
