# Generated by Django 6.0.2 on 2026-02-23 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0011_ancestry_style_date_qualifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='linked_person',
            field=models.ForeignKey(blank=True, help_text='The Person record in the family tree that represents this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_membership', to='families.person'),
        ),
    ]
