# Generated by Django 6.0.2 on 2026-02-23 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0012_add_linked_person_to_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', help_text='Verification status', max_length=20)),
                ('provided_birth_date', models.DateField(blank=True, help_text='Birth date provided by user for verification', null=True)),
                ('provided_birth_place', models.CharField(blank=True, help_text='Birth place provided for verification', max_length=255)),
                ('provided_mother_name', models.CharField(blank=True, help_text="Mother's name provided for verification", max_length=255)),
                ('provided_father_name', models.CharField(blank=True, help_text="Father's name provided for verification", max_length=255)),
                ('name_match_score', models.FloatField(default=0.0, help_text='How closely the names matched (0-1)')),
                ('auto_matched', models.BooleanField(default=False, help_text='Whether this was auto-suggested based on name match')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('family', models.ForeignKey(help_text='Family space context', on_delete=django.db.models.deletion.CASCADE, related_name='person_claims', to='families.familyspace')),
                ('person', models.ForeignKey(help_text='Person record being claimed', on_delete=django.db.models.deletion.CASCADE, related_name='identity_claims', to='families.person')),
                ('user', models.ForeignKey(help_text='User claiming this identity', on_delete=django.db.models.deletion.CASCADE, related_name='person_claims', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin who verified/rejected (if manual)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person Claim',
                'verbose_name_plural': 'Person Claims',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'person')},
            },
        ),
    ]
