# Generated by Django 6.0.2 on 2026-02-23 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0013_add_person_claim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this person was deleted', null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this person', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Whether this person has been soft-deleted'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this relationship was deleted', null=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this relationship', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationships_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relationship',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Whether this relationship has been soft-deleted'),
        ),
        migrations.CreateModel(
            name='DeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('PERSON', 'Person'), ('RELATIONSHIP', 'Relationship'), ('ALBUM', 'Album'), ('GEDCOM', 'GEDCOM Import')], help_text='Type of object to delete', max_length=20)),
                ('object_id', models.PositiveIntegerField(help_text='ID of the object to delete')),
                ('object_repr', models.CharField(help_text='String representation of the object', max_length=255)),
                ('object_data', models.JSONField(blank=True, help_text='Snapshot of object data for review', null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for requesting deletion')),
                ('reviewer_notes', models.TextField(blank=True, help_text='Notes from the reviewer')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled by Requester')], default='PENDING', help_text='Current status of the request', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When deletion was requested')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the request was reviewed', null=True)),
                ('permanent_delete', models.BooleanField(default=False, help_text='If true, permanently delete. If false, soft delete.')),
                ('family', models.ForeignKey(help_text='The family space this deletion is for', on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to='families.familyspace')),
                ('requester', models.ForeignKey(help_text='User who requested the deletion', on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, help_text='Admin who reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deletion Request',
                'verbose_name_plural': 'Deletion Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('RESTORE', 'Restored'), ('IMPORT', 'Imported'), ('EXPORT', 'Exported'), ('MERGE', 'Merged'), ('CLAIM', 'Claimed Identity')], help_text='Type of action performed', max_length=20)),
                ('object_type', models.CharField(choices=[('PERSON', 'Person'), ('RELATIONSHIP', 'Relationship'), ('ALBUM', 'Album'), ('PHOTO', 'Photo'), ('EVENT', 'Event'), ('FAMILY', 'Family Space'), ('GEDCOM', 'GEDCOM Import'), ('MEMBERSHIP', 'Membership')], help_text='Type of object affected', max_length=20)),
                ('object_id', models.PositiveIntegerField(help_text='ID of the affected object')),
                ('object_repr', models.CharField(help_text='String representation of the object at time of action', max_length=255)),
                ('changes', models.JSONField(blank=True, help_text='JSON dict of field changes (for updates)', null=True)),
                ('previous_data', models.JSONField(blank=True, help_text='JSON snapshot of object before deletion (for recovery)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser/client user agent', max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this action occurred')),
                ('family', models.ForeignKey(help_text='The family space this action was performed in', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='families.familyspace')),
                ('user', models.ForeignKey(help_text='User who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['family', 'timestamp'], name='families_au_family__510ab7_idx'), models.Index(fields=['object_type', 'object_id'], name='families_au_object__180879_idx'), models.Index(fields=['user', 'timestamp'], name='families_au_user_id_440f0a_idx')],
            },
        ),
    ]
