# Generated by Django 6.0.2 on 2026-02-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0014_add_soft_delete_and_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.CharField(choices=[('PARENT_CHILD', 'Parent-Child'), ('SPOUSE', 'Spouse'), ('GRANDPARENT', 'Grandparent-Grandchild'), ('GREAT_GRANDPARENT', 'Great-Grandparent'), ('GREAT_GRANDPARENT_2X', '2nd Great-Grandparent'), ('GREAT_GRANDPARENT_3X', '3rd Great-Grandparent'), ('GREAT_GRANDPARENT_4X', '4th Great-Grandparent'), ('GREAT_GRANDPARENT_5X', '5th Great-Grandparent'), ('GREAT_GRANDPARENT_6X', '6th Great-Grandparent')], help_text='Type of relationship', max_length=25),
        ),
    ]
