# Generated by Django 6.0.2 on 2026-03-22 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0015_add_extended_relationships"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CrossSpacePersonLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("CONFIRMED", "Confirmed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PROPOSED",
                        help_text="Link status",
                        max_length=20,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(default=0, help_text="Match confidence (0-100)"),
                ),
                (
                    "match_reasons",
                    models.TextField(
                        blank=True,
                        default="[]",
                        help_text="JSON array explaining the match",
                    ),
                ),
                (
                    "confirmed_by_space1",
                    models.BooleanField(
                        default=False, help_text="Confirmed by person1's family admin"
                    ),
                ),
                (
                    "confirmed_by_space2",
                    models.BooleanField(
                        default=False, help_text="Confirmed by person2's family admin"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When link was proposed"
                    ),
                ),
                (
                    "person1",
                    models.ForeignKey(
                        help_text="Person in one family space",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cross_space_links_as_person1",
                        to="families.person",
                    ),
                ),
                (
                    "person2",
                    models.ForeignKey(
                        help_text="Same person in another family space",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cross_space_links_as_person2",
                        to="families.person",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        help_text="User who proposed the link",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cross_space_links_proposed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cross-Space Person Link",
                "verbose_name_plural": "Cross-Space Person Links",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MemoryStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the story or memory", max_length=200
                    ),
                ),
                ("content", models.TextField(help_text="The story content")),
                (
                    "story_type",
                    models.CharField(
                        choices=[
                            ("MEMORY", "Memory"),
                            ("STORY", "Story"),
                            ("TRIBUTE", "Tribute"),
                            ("BIOGRAPHY", "Biography"),
                            ("MILESTONE", "Life Milestone"),
                            ("TRADITION", "Family Tradition"),
                            ("RECIPE", "Family Recipe"),
                            ("LESSON", "Life Lesson"),
                        ],
                        default="MEMORY",
                        help_text="Type of memory",
                        max_length=20,
                    ),
                ),
                (
                    "date_of_memory",
                    models.DateField(
                        blank=True, help_text="When this memory took place", null=True
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Where this memory took place",
                        max_length=200,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Feature this memory on the person's profile",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Make visible to shared/guest viewers"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this memory has been viewed",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this memory was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this memory was last modified"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Who wrote this memory",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        help_text="The person this memory is about",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memories",
                        to="families.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Memory/Story",
                "verbose_name_plural": "Memories & Stories",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MemoryMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("PHOTO", "Photo"),
                            ("VIDEO", "Video"),
                            ("AUDIO", "Audio Recording"),
                            ("DOCUMENT", "Document"),
                        ],
                        default="PHOTO",
                        help_text="Type of media",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The media file", upload_to="museum/%Y/%m/"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail for videos",
                        null=True,
                        upload_to="museum/thumbs/%Y/%m/",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, help_text="Caption for this media", max_length=500
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this media was uploaded"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="Who uploaded this media",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_memory_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "memory",
                    models.ForeignKey(
                        help_text="The memory this media belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="families.memorystory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Memory Media",
                "verbose_name_plural": "Memory Media",
                "ordering": ["order", "uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="MemoryComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Comment text", max_length=1000),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this comment was posted"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this comment was last edited"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Who wrote this comment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "memory",
                    models.ForeignKey(
                        help_text="The memory being commented on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="families.memorystory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Memory Comment",
                "verbose_name_plural": "Memory Comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MuseumShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "share_type",
                    models.CharField(
                        choices=[
                            ("MEMORY", "Single Memory"),
                            ("PERSON", "Person's Memories"),
                            ("MUSEUM", "Entire Museum"),
                        ],
                        default="MEMORY",
                        help_text="What is being shared",
                        max_length=20,
                    ),
                ),
                (
                    "shared_with_email",
                    models.EmailField(
                        blank=True, help_text="Email of the recipient", max_length=254
                    ),
                ),
                (
                    "share_token",
                    models.CharField(
                        editable=False,
                        help_text="Unique token for share link",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "is_public_link",
                    models.BooleanField(
                        default=False, help_text="Anyone with the link can view"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optional personal message",
                        max_length=500,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When share expires (null = never)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this share is currently active"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this share has been viewed",
                    ),
                ),
                (
                    "last_viewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the share was last viewed",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When share was created"
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        blank=True,
                        help_text="Family whose entire museum is being shared",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="museum_shares",
                        to="families.familyspace",
                    ),
                ),
                (
                    "memory",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific memory being shared",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="families.memorystory",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person whose memories are being shared",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="museum_shares",
                        to="families.person",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        help_text="User who created this share",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="museum_shares_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who received the share (if registered)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="museum_shares_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Museum Share",
                "verbose_name_plural": "Museum Shares",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MemoryReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("LIKE", "👍 Like"),
                            ("LOVE", "❤️ Love"),
                            ("LAUGH", "😂 Laugh"),
                            ("CRY", "😢 Touching"),
                            ("WOW", "😮 Wow"),
                        ],
                        default="LIKE",
                        help_text="Type of reaction",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When reaction was added"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Who reacted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "memory",
                    models.ForeignKey(
                        help_text="The memory being reacted to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="families.memorystory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Memory Reaction",
                "verbose_name_plural": "Memory Reactions",
                "unique_together": {("memory", "user")},
            },
        ),
        migrations.CreateModel(
            name="SharedAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("VIEWER", "View Only"),
                            ("LIMITED", "Limited (ancestors only)"),
                        ],
                        default="VIEWER",
                        help_text="Level of access granted",
                        max_length=20,
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When access was granted"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When access expires (null = never)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this access grant is currently active",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        help_text="Family space being shared",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_access_grants",
                        to="families.familyspace",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        help_text="User who granted the access",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_grants_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User with shared access",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_family_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Shared Access",
                "verbose_name_plural": "Shared Access Grants",
                "ordering": ["-granted_at"],
                "unique_together": {("user", "family")},
            },
        ),
        migrations.CreateModel(
            name="SpaceAccessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optional message to the family admins",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("DENIED", "Denied"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        help_text="Request status",
                        max_length=20,
                    ),
                ),
                (
                    "reviewer_notes",
                    models.TextField(
                        blank=True, help_text="Notes from the reviewer", max_length=500
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the request was reviewed", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When request was created"
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        help_text="User requesting access",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="space_access_requests_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who reviewed this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_requests_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_family",
                    models.ForeignKey(
                        help_text="Family space being requested",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_requests",
                        to="families.familyspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Space Access Request",
                "verbose_name_plural": "Space Access Requests",
                "ordering": ["-created_at"],
                "unique_together": {("requester", "target_family")},
            },
        ),
    ]
