# Generated by Django 6.0.2 on 2026-03-21 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0016_add_living_museum_and_sharing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True,
                help_text="Members who liked this post",
                related_name="liked_family_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tagged_people",
            field=models.ManyToManyField(
                blank=True,
                help_text="Family members tagged in this post",
                related_name="tagged_posts",
                to="families.person",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Optional video attachment",
                null=True,
                upload_to="posts/videos/%Y/%m/",
            ),
        ),
    ]
