# Generated by Django 6.0.2 on 2026-03-21 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0017_post_timeline_enhancements"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("conversation_type", models.CharField(choices=[("FAMILY", "Family Chat"), ("DIRECT", "Direct Message"), ("BRANCH", "Family Branch"), ("EVENT", "Event Chat")], default="FAMILY", help_text="What kind of conversation this is", max_length=20)),
                ("title", models.CharField(blank=True, help_text="Optional custom conversation title", max_length=200)),
                ("direct_key", models.CharField(blank=True, help_text="Stable unique key for direct conversations", max_length=120, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("branch_root", models.ForeignKey(blank=True, help_text="Root person for a family-branch conversation", null=True, on_delete=django.db.models.deletion.CASCADE, related_name="branch_conversations", to="families.person")),
                ("created_by", models.ForeignKey(help_text="User who created the conversation", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_chat_conversations", to=settings.AUTH_USER_MODEL)),
                ("event", models.ForeignKey(blank=True, help_text="Event this conversation is attached to", null=True, on_delete=django.db.models.deletion.CASCADE, related_name="chat_conversations", to="families.event")),
                ("family", models.ForeignKey(help_text="Family space this conversation belongs to", on_delete=django.db.models.deletion.CASCADE, related_name="chat_conversations", to="families.familyspace")),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["family", "conversation_type"], name="families_ch_family__ff7ee2_idx"),
                    models.Index(fields=["family", "-updated_at"], name="families_ch_family__6f4016_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChatConversationMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(max_length=4000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("author", models.ForeignKey(help_text="User who sent this message", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="family_conversation_messages", to=settings.AUTH_USER_MODEL)),
                ("conversation", models.ForeignKey(help_text="Conversation this message belongs to", on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="families.chatconversation")),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [models.Index(fields=["conversation", "created_at"], name="families_ch_convers_582784_idx")],
            },
        ),
        migrations.CreateModel(
            name="ChatConversationParticipant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="participants", to="families.chatconversation")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="family_chat_participations", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["joined_at"],
                "unique_together": {("conversation", "user")},
            },
        ),
        migrations.CreateModel(
            name="ChatMessageReadReceipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("read_at", models.DateTimeField(auto_now=True)),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="read_receipts", to="families.chatconversationmessage")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="chat_read_receipts", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-read_at"],
                "unique_together": {("message", "user")},
            },
        ),
    ]
