# Generated by Django 6.0.2 on 2026-03-21 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0018_unified_realtime_messaging"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="notify_members",
            field=models.BooleanField(default=True, help_text="Notify family members when this event is created or updated"),
        ),
        migrations.AddField(
            model_name="event",
            name="reminder_days_before",
            field=models.PositiveIntegerField(default=7, help_text="How many days before the event reminders should be sent"),
        ),
        migrations.AddField(
            model_name="event",
            name="send_reminders",
            field=models.BooleanField(default=True, help_text="Send reminder notifications before the event"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("BIRTHDAY", "Birthday"),
                    ("REUNION", "Family Reunion"),
                    ("HOLIDAY", "Holiday Gathering"),
                    ("ANNIVERSARY", "Anniversary"),
                    ("FUNERAL", "Funeral"),
                    ("MEMORIAL", "Memorial"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                help_text="Type of event",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EventReminderLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reminder_for_date", models.DateField(help_text="The event date this reminder was sent for")),
                ("notified_at", models.DateTimeField(auto_now_add=True)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reminder_logs", to="families.event")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="event_reminder_logs", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-notified_at"],
                "unique_together": {("event", "user", "reminder_for_date")},
            },
        ),
    ]
