# Generated by Django 6.0.2 on 2026-03-24 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0023_family_milestone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingPersonChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                        ],
                        max_length=10,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="TreeMergeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED_SOURCE", "Approved by Source"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        help_text="Merge request status",
                        max_length=20,
                    ),
                ),
                (
                    "proposed_links",
                    models.JSONField(
                        default=list, help_text="JSON array of proposed person matches"
                    ),
                ),
                (
                    "merge_type",
                    models.CharField(
                        choices=[("LINK", "Link Only"), ("COPY", "Copy Persons")],
                        default="LINK",
                        help_text="Whether to link or copy persons",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes about the merge"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Tree Merge Request",
                "verbose_name_plural": "Tree Merge Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="chatconversation",
            new_name="families_ch_family__e3b105_idx",
            old_name="families_ch_family__ff7ee2_idx",
        ),
        migrations.RenameIndex(
            model_name="chatconversation",
            new_name="families_ch_family__bb68e1_idx",
            old_name="families_ch_family__6f4016_idx",
        ),
        migrations.RenameIndex(
            model_name="chatconversationmessage",
            new_name="families_ch_convers_dba134_idx",
            old_name="families_ch_convers_582784_idx",
        ),
        migrations.AlterField(
            model_name="album",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text="Event this album is associated with (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="albums",
                to="families.event",
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="primary_person",
            field=models.ForeignKey(
                blank=True,
                help_text="Highlight person this album is centered on (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="person_albums",
                to="families.person",
            ),
        ),
        migrations.AlterField(
            model_name="familymilestone",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who added this milestone",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_milestones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="familymilestone",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked event (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="milestones",
                to="families.event",
            ),
        ),
        migrations.AlterField(
            model_name="familymilestone",
            name="family",
            field=models.ForeignKey(
                help_text="Family this milestone belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milestones",
                to="families.familyspace",
            ),
        ),
        migrations.AlterField(
            model_name="familymilestone",
            name="person",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked person (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="milestones",
                to="families.person",
            ),
        ),
        migrations.AlterField(
            model_name="lifestory",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this life story",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_life_stories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lifestory",
            name="person",
            field=models.ForeignKey(
                help_text="Person this life story belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="life_stories",
                to="families.person",
            ),
        ),
        migrations.AlterField(
            model_name="lifestorysection",
            name="life_story",
            field=models.ForeignKey(
                help_text="Parent life story",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="families.lifestory",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text="Event this media belongs to (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="media_items",
                to="families.event",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="primary_person",
            field=models.ForeignKey(
                blank=True,
                help_text="Person this media is centered on (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_media_items",
                to="families.person",
            ),
        ),
        migrations.AlterField(
            model_name="timecapsule",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this capsule",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_time_capsules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="timecapsule",
            name="family",
            field=models.ForeignKey(
                help_text="Family this capsule belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_capsules",
                to="families.familyspace",
            ),
        ),
        migrations.AddField(
            model_name="pendingpersonchange",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="person_change_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pendingpersonchange",
            name="family",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pending_person_changes",
                to="families.familyspace",
            ),
        ),
        migrations.AddField(
            model_name="pendingpersonchange",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_changes",
                to="families.person",
            ),
        ),
        migrations.AddField(
            model_name="pendingpersonchange",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="person_change_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="treemergerequest",
            name="approved_by_source",
            field=models.ForeignKey(
                blank=True,
                help_text="Source family admin who approved",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merge_requests_approved_source",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="treemergerequest",
            name="approved_by_target",
            field=models.ForeignKey(
                blank=True,
                help_text="Target family admin who approved",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merge_requests_approved_target",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="treemergerequest",
            name="from_family",
            field=models.ForeignKey(
                help_text="Source family tree",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="merge_requests_from",
                to="families.familyspace",
            ),
        ),
        migrations.AddField(
            model_name="treemergerequest",
            name="requested_by",
            field=models.ForeignKey(
                help_text="User who requested the merge",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merge_requests_initiated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="treemergerequest",
            name="to_family",
            field=models.ForeignKey(
                help_text="Target family tree",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="merge_requests_to",
                to="families.familyspace",
            ),
        ),
    ]
