# Generated by Django 6.0.2 on 2026-03-27 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0024_pendingpersonchange_treemergerequest_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrayerRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short title for the prayer request", max_length=200
                    ),
                ),
                ("content", models.TextField(help_text="Full prayer request details")),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=False, help_text="Hide author identity from other users"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open - Requesting Prayer"),
                            ("ANSWERED", "Answered - Praise Report"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        help_text="Current status of the prayer request",
                        max_length=20,
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False, help_text="Pin to top of prayer list"
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False, help_text="Hide from public view (moderation)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who posted the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prayer_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        blank=True,
                        help_text="Family space (null for global prayers)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prayer_requests",
                        to="families.familyspace",
                    ),
                ),
                (
                    "praying_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users who committed to pray",
                        related_name="prayers_committed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prayer Request",
                "verbose_name_plural": "Prayer Requests",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrayerReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Reply content", max_length=2000),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=False, help_text="Hide author identity"
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False, help_text="Hide from view (moderation)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who wrote this reply",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prayer_replies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prayer_request",
                    models.ForeignKey(
                        help_text="The prayer request this replies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="families.prayerrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prayer Reply",
                "verbose_name_plural": "Prayer Replies",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrayerTestimony",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The testimony of how prayer was answered"
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=False, help_text="Keep testimony anonymous"
                    ),
                ),
                (
                    "answered_date",
                    models.DateField(
                        blank=True, help_text="Date the prayer was answered", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who wrote this testimony",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prayer_testimonies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prayer_request",
                    models.OneToOneField(
                        help_text="The prayer request this testimony is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimony",
                        to="families.prayerrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prayer Testimony",
                "verbose_name_plural": "Prayer Testimonies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="prayerrequest",
            index=models.Index(
                fields=["family", "-created_at"], name="families_pr_family__8ba028_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prayerrequest",
            index=models.Index(
                fields=["status", "-created_at"], name="families_pr_status_b803e6_idx"
            ),
        ),
    ]
