# Generated by Django 6.0.2 on 2026-03-29 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0028_invite_accepted_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ThreadCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Category name", max_length=50)),
                (
                    "color",
                    models.CharField(
                        default="#6366f1",
                        help_text="Hex color code for the category badge",
                        max_length=7,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon identifier (e.g., 'dna', 'tree', 'photo')",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what this category is for"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this category is available for new posts",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in which categories appear"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "family",
                    models.ForeignKey(
                        help_text="The family space this category belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thread_categories",
                        to="families.familyspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thread Category",
                "verbose_name_plural": "Thread Categories",
                "ordering": ["display_order", "name"],
                "unique_together": {("family", "name")},
            },
        ),
        migrations.CreateModel(
            name="ThreadPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Post title", max_length=300)),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Post body content (supports markdown)"
                    ),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("DISCUSSION", "Discussion"),
                            ("QUESTION", "Question"),
                            ("DISCOVERY", "Discovery"),
                            ("RESEARCH", "Research Help"),
                            ("PHOTO", "Photo Share"),
                            ("DNA", "DNA Discussion"),
                            ("LINK", "Link"),
                        ],
                        default="DISCUSSION",
                        help_text="Type of post",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional image attachment",
                        null=True,
                        upload_to="threads/%Y/%m/",
                    ),
                ),
                (
                    "link_url",
                    models.URLField(blank=True, help_text="Optional external link"),
                ),
                (
                    "link_title",
                    models.CharField(
                        blank=True, help_text="Title for external link", max_length=300
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False, help_text="Pin this post to the top"
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(default=False, help_text="Prevent new replies"),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False, help_text="Hide this post (moderation)"
                    ),
                ),
                (
                    "is_answered",
                    models.BooleanField(
                        default=False, help_text="Mark question as answered"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, help_text="Number of views"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The user who created this post",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="thread_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional category/flair for the post",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="families.threadcategory",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        help_text="The family space this post belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thread_posts",
                        to="families.familyspace",
                    ),
                ),
                (
                    "tagged_people",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Family tree members mentioned in this post",
                        related_name="thread_mentions",
                        to="families.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thread Post",
                "verbose_name_plural": "Thread Posts",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ThreadBookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, help_text="Optional personal note"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who bookmarked this post",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thread_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        help_text="The bookmarked post",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="families.threadpost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thread Bookmark",
                "verbose_name_plural": "Thread Bookmarks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ThreadReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Reply content (supports markdown)"),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False, help_text="Hide this reply (moderation)"
                    ),
                ),
                (
                    "is_edited",
                    models.BooleanField(
                        default=False, help_text="Whether this reply has been edited"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The user who wrote this reply",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="thread_replies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent reply for nested comments",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="families.threadreply",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        help_text="The post this reply belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="families.threadpost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thread Reply",
                "verbose_name_plural": "Thread Replies",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ThreadVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote_type",
                    models.CharField(
                        choices=[("UPVOTE", "Upvote"), ("DOWNVOTE", "Downvote")],
                        help_text="Type of vote",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        help_text="The post being voted on",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="families.threadpost",
                    ),
                ),
                (
                    "reply",
                    models.ForeignKey(
                        blank=True,
                        help_text="The reply being voted on",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="families.threadreply",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who cast this vote",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thread_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Thread Vote",
                "verbose_name_plural": "Thread Votes",
            },
        ),
        migrations.AddIndex(
            model_name="threadpost",
            index=models.Index(
                fields=["family", "-created_at"], name="families_th_family__1fe02e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="threadpost",
            index=models.Index(
                fields=["family", "category"], name="families_th_family__b2dbbc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="threadpost",
            index=models.Index(
                fields=["author"], name="families_th_author__84f801_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="threadbookmark",
            unique_together={("user", "post")},
        ),
        migrations.AddIndex(
            model_name="threadreply",
            index=models.Index(
                fields=["post", "created_at"], name="families_th_post_id_8a485b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="threadreply",
            index=models.Index(
                fields=["parent"], name="families_th_parent__ad2e20_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="threadvote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("post__isnull", False)),
                fields=("user", "post"),
                name="unique_user_post_vote",
            ),
        ),
        migrations.AddConstraint(
            model_name="threadvote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reply__isnull", False)),
                fields=("user", "reply"),
                name="unique_user_reply_vote",
            ),
        ),
        migrations.AddConstraint(
            model_name="threadvote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("post__isnull", False), ("reply__isnull", True)),
                    models.Q(("post__isnull", True), ("reply__isnull", False)),
                    _connector="OR",
                ),
                name="vote_on_post_or_reply",
            ),
        ),
    ]
